"""empty message

Revision ID: a87b3830cabd
Revises: 2cf5c0154920
Create Date: 2024-04-05 23:44:23.456541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87b3830cabd'
down_revision = '2cf5c0154920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('income', sa.String(length=80), nullable=False),
    sa.Column('necessary_bills', sa.String(length=80), nullable=False),
    sa.Column('necessary_bills_amount', sa.Integer(), nullable=False),
    sa.Column('necessary_purchases', sa.String(length=80), nullable=False),
    sa.Column('necessary_purchases_amount', sa.Integer(), nullable=False),
    sa.Column('other_purchases', sa.String(length=80), nullable=True),
    sa.Column('other_purchases_amount', sa.Integer(), nullable=True),
    sa.Column('saving_purpose', sa.String(length=80), nullable=True),
    sa.Column('savings', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('name')

    op.drop_table('monthly_plan')
    # ### end Alembic commands ###
